version: '3.7'

services:
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: msch13
      POSTGRES_PASSWORD: user13
    volumes:
      - ./postgres_data:/var/lib/postgressql/data
